# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :tests do
    run_tests(project: "rncircletest3_3611.xcodeproj", scheme: "rncircletest3_3611")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    produce(
      username: "support@crowdbotics.com",
      app_identifier: "com.crowdbotics.rncircletest3-3611",
      app_name: "rncircletest3-3611",
      team_name: "Crowdbotics Corporation",
      itc_team_name: "Crowdbotics Corporation"
    )
    increment_build_number(xcodeproj: "rncircletest3_3611.xcodeproj")
    update_app_identifier(
      xcodeproj: "rncircletest3_3611.xcodeproj",
      plist_path: "rncircletest3_3611/Info.plist",
      app_identifier: "com.crowdbotics.rncircletest3-3611"
    )
    update_project_team(path: "rncircletest3_3611.xcodeproj", teamid: "6YKR59QXKM")
    match(type: "appstore", readonly: is_ci)
    build_app(
      scheme: "rncircletest3_3611",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight(email: "dan+testflight@crowdbotics.com")
  end
end
